# Example dbt profiles.yml for Trino
trino_profile:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino
      port: 8080
      user: dbt
      database: hive        # catalog
      schema: default       # schema
      http_scheme: http
      threads: 4