name: "ecom_analytics"
version: 1.0.0
config-version: 2

profile: "ecom_analytics"

model-paths: ["models"]
models:
  ecom_analytics:
    +materialized: view
    gold:
      +materialized: incremental
      +on_schema_change: sync_all_columns