version: 2

models:
  - name: fct_sales_minute
    description: Minute-level GMV + paid order counts (paid_only from silver).
    columns:
      - name: minute_bucket
        tests: [not_null, unique]        # unique key for incremental
      - name: gmv
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "gmv >= 0"
      - name: paid_orders
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "paid_orders >= 0"
      - name: processed_ts
        tests: [not_null]

sources:
  - name: silver
    schema: silver
    freshness:
      warn_after: {count: 10, period: minute}
      error_after: {count: 30, period: minute}
    loaded_at_field: event_ts
    tables:
      - name: orders_clean
      - name: order_payments_enriched    # fixes your earlier freshness warning
