name: ecommerce_analytics
version: 1.0.0
config-version: 2

profile: trino_lake

model-paths: ["models"]
models:
  ecommerce_analytics:
    +materialized: view
    gold:
      +materialized: incremental
      +on_schema_change: sync_all_columns
