ecom_analytics:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino
      port: 8080
      user: dbt
      http_scheme: http
      database: delta
      schema: gold
      threads: 4
      session_properties:
        query_max_memory: 1GB
        query_max_total_memory: 2GB
        task_concurrency: 2