global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'auth'
    metrics_path: /auth/metrics
    static_configs: [{ targets: ['auth:8000'] }]

  - job_name: 'catalog'
    metrics_path: /catalog/metrics
    static_configs: [{ targets: ['catalog:8000'] }]

  - job_name: 'order'
    metrics_path: /order/metrics
    static_configs: [{ targets: ['order:8000'] }]

  - job_name: 'cart'
    metrics_path: /cart/metrics
    static_configs: [{ targets: ['cart:8000'] }]

  - job_name: 'payment'
    metrics_path: /payment/metrics
    static_configs: [{ targets: ['payment:8000'] }]

  - job_name: 'shipping'
    metrics_path: /shipping/metrics
    static_configs: [{ targets: ['shipping:8000'] }]

  - job_name: 'notifications'
    metrics_path: /notifications/metrics
    static_configs: [{ targets: ['notifications:8000'] }]

  - job_name: 'postgres'
    static_configs: [{ targets: ['postgres-exporter:9187'] }]

  - job_name: 'redis'
    static_configs: [{ targets: ['redis-exporter:9121'] }]

  - job_name: 'kafka'
    static_configs: [{ targets: ['kafka-exporter:9308'] }]

  - job_name: spark-master
    metrics_path: /metrics/master/prometheus
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: spark-worker
    metrics_path: /metrics/prometheus
    static_configs:
      - targets:
          - 'spark-worker:8081'

  - job_name: 'trino'
    static_configs: [{ targets: ['trino:8080'] }]
    metrics_path: /metrics

  # Airflow Metrics Configuration
  - job_name: 'airflow-webserver'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-webserver:8080']
    # Optional: Add basic authentication if needed
    basic_auth:
      username: admin
      password: admin

  - job_name: 'airflow-scheduler'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-scheduler:8793']  # Scheduler metrics port
